import { Comment } from "./types/commentsResult";

export const fakeData: Comment[] = [
    {
        "id": "Ugyl1P04gf0jUNRglU54AaABAg",
        "textDisplay": "Will I be charged after the frontegg trial ends?",
        "authorDisplayName": "GamesGVG",
        "publishedAt": "2022-08-16T22:09:28Z",
        "updatedAt": "2022-08-16T22:09:28Z",
        "likeCount": 0,
        "sentimentScore": -3,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgwNUdOLLgVK7ocnQw94AaABAg",
        "textDisplay": "y'all! the most played; I am dead.",
        "authorDisplayName": "Pranshu Chawla",
        "publishedAt": "2022-08-11T20:29:10Z",
        "updatedAt": "2022-08-11T20:29:10Z",
        "likeCount": 0,
        "sentimentScore": -3,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugx_qzOEbsL9-z7_MR94AaABAg",
        "textDisplay": "y'all the most played, I am dead.",
        "authorDisplayName": "Pranshu Chawla",
        "publishedAt": "2022-08-11T20:28:42Z",
        "updatedAt": "2022-08-11T20:28:42Z",
        "likeCount": 0,
        "sentimentScore": -3,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgxzX07Ot2XVvD0On8l4AaABAg",
        "textDisplay": "cool video I wish there would be more backend and more code in detail :)",
        "authorDisplayName": "Daniel T",
        "publishedAt": "2022-08-11T12:23:18Z",
        "updatedAt": "2022-08-11T12:23:18Z",
        "likeCount": 0,
        "sentimentScore": 2,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugxpv6T62fXxbltjkWF4AaABAg",
        "textDisplay": "My Node version is 14.15.0 and I have an application's dependency on it! What should I do?",
        "authorDisplayName": "Md Abdul Momin",
        "publishedAt": "2022-08-10T04:04:05Z",
        "updatedAt": "2022-08-10T04:04:05Z",
        "likeCount": 0,
        "sentimentScore": 0,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgxlbJudKkypASaUUmR4AaABAg",
        "textDisplay": "get a better mic ... and better content - it's a genuine advise / unless you collect subscribers without a real object",
        "authorDisplayName": "Bek Brace",
        "publishedAt": "2022-08-07T11:53:05Z",
        "updatedAt": "2022-08-07T11:53:05Z",
        "likeCount": 0,
        "sentimentScore": 4,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugymt2Q1oy2AcbMdqiF4AaABAg",
        "textDisplay": "you need a better mic",
        "authorDisplayName": "Exordium",
        "publishedAt": "2022-08-06T11:53:31Z",
        "updatedAt": "2022-08-06T11:53:31Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "hungarian",
        "languageCode": "hu"
    },
    {
        "id": "Ugyv2da6gC67G4eGm1t4AaABAg",
        "textDisplay": "ayu theme?",
        "authorDisplayName": "Afin",
        "publishedAt": "2022-08-04T19:03:07Z",
        "updatedAt": "2022-08-04T19:03:07Z",
        "likeCount": 0,
        "sentimentScore": 0,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugya78wWJo_qAz3hNiV4AaABAg",
        "textDisplay": "good!",
        "authorDisplayName": "EguchiYuuki",
        "publishedAt": "2022-08-04T11:39:13Z",
        "updatedAt": "2022-08-04T11:39:13Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "croatian",
        "languageCode": "hr"
    },
    {
        "id": "UgxynZZskAx4WuzEHrl4AaABAg",
        "textDisplay": "quality content ! thanks for sharing",
        "authorDisplayName": "Fri Chakir",
        "publishedAt": "2022-08-04T11:10:15Z",
        "updatedAt": "2022-08-04T11:10:15Z",
        "likeCount": 0,
        "sentimentScore": 4,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugwc71Nyp8lnY0U_CYp4AaABAg",
        "textDisplay": "C'est pas la petite amie de Benjamin code... Je m'abonne",
        "authorDisplayName": "Emmanuel Kouassi",
        "publishedAt": "2022-08-04T08:00:13Z",
        "updatedAt": "2022-08-04T08:00:45Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "french",
        "languageCode": "fr"
    },
    {
        "id": "Ugx_YBuwgqN1E-LFUud4AaABAg",
        "textDisplay": "Ladies, please don't drive our focus away, atleast while coding. Brain is too sensitive.",
        "authorDisplayName": "Juan Roman",
        "publishedAt": "2022-08-03T16:53:42Z",
        "updatedAt": "2022-08-03T16:53:42Z",
        "likeCount": 1,
        "sentimentScore": 1,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgzVxfo2TpW5nIxahQ54AaABAg",
        "textDisplay": "Thank you for sharing.",
        "authorDisplayName": "m4rc0 k!tt3l",
        "publishedAt": "2022-08-03T13:53:15Z",
        "updatedAt": "2022-08-03T13:53:15Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "norwegian",
        "languageCode": "no"
    },
    {
        "id": "UgzOi9Oxb8DOCotffRR4AaABAg",
        "textDisplay": "I'm feeling so dumb because I did exactly as you did to integrate frontegg with my react app and the button to login never showed 🤡 but great video overall Jackie, you should do more videos like this!",
        "authorDisplayName": "Flávia Miranda",
        "publishedAt": "2022-08-03T13:51:09Z",
        "updatedAt": "2022-08-03T13:51:09Z",
        "likeCount": 0,
        "sentimentScore": 3,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgwCWF-rwgSv4SElWbt4AaABAg",
        "textDisplay": "How ling time you learn JS?",
        "authorDisplayName": "Bazil Safronov",
        "publishedAt": "2022-08-03T13:20:12Z",
        "updatedAt": "2022-08-03T13:20:12Z",
        "likeCount": 0,
        "sentimentScore": 0,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgzQ4lYXoUEak6zgnPZ4AaABAg",
        "textDisplay": "I love text books as they are more fun to read and even if I have internet problems. I can still read the books. :)",
        "authorDisplayName": "Jonathan Steadman",
        "publishedAt": "2022-08-02T13:22:07Z",
        "updatedAt": "2022-08-02T13:22:07Z",
        "likeCount": 1,
        "sentimentScore": 5,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugzq3FOzhRATObEao514AaABAg",
        "textDisplay": "I wanna be a software engineer anyway you inspire me. :)\nThanks from Jonathan Steadman.",
        "authorDisplayName": "Jonathan Steadman",
        "publishedAt": "2022-08-02T13:19:51Z",
        "updatedAt": "2022-08-02T13:19:51Z",
        "likeCount": 1,
        "sentimentScore": "not available",
        "language": "swedish",
        "languageCode": "sv"
    },
    {
        "id": "UgxvvAXhUMFoT8rOprl4AaABAg",
        "textDisplay": "good",
        "authorDisplayName": "yondaime",
        "publishedAt": "2022-08-01T19:17:04Z",
        "updatedAt": "2022-08-01T19:17:04Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "croatian",
        "languageCode": "hr"
    },
    {
        "id": "UgwGd-77h6vNIwMMYsp4AaABAg",
        "textDisplay": "Очень интересно",
        "authorDisplayName": "Dante Rage",
        "publishedAt": "2022-08-01T18:40:52Z",
        "updatedAt": "2022-08-01T18:40:52Z",
        "likeCount": 1,
        "sentimentScore": "not available",
        "language": "ukrainian",
        "languageCode": "uk"
    },
    {
        "id": "UgywPIqVqIjEwnoFwX54AaABAg",
        "textDisplay": "I'm happy to know that i'm not the only one pretending to look smart by buying books. Joke. Nice video... I almost have the same books :)",
        "authorDisplayName": "Agustin Jaimes",
        "publishedAt": "2022-08-01T11:59:56Z",
        "updatedAt": "2022-08-01T12:00:14Z",
        "likeCount": 0,
        "sentimentScore": 8,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugyvvw80uX3nhQLMcBR4AaABAg",
        "textDisplay": "Hello Jackie, nice one. Could you please tell me more about your keyboard? :D",
        "authorDisplayName": "Greg Dask",
        "publishedAt": "2022-08-01T10:43:33Z",
        "updatedAt": "2022-08-01T10:43:33Z",
        "likeCount": 0,
        "sentimentScore": 4,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgzavBYhCXI8La2JjnR4AaABAg",
        "textDisplay": "Beauty, smart and coder\n\nI fall in love",
        "authorDisplayName": "Carlos Eduardo Olivares Rodriguez",
        "publishedAt": "2022-07-31T23:24:25Z",
        "updatedAt": "2022-07-31T23:24:25Z",
        "likeCount": 0,
        "sentimentScore": 7,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgzLlzcafUfYJDjxgD54AaABAg",
        "textDisplay": "*sus*",
        "authorDisplayName": "Diego González",
        "publishedAt": "2022-07-31T20:38:33Z",
        "updatedAt": "2022-07-31T20:38:33Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "lithuanian",
        "languageCode": "lt"
    },
    {
        "id": "UgwTXl-21FU76OfIh914AaABAg",
        "textDisplay": "very helpful tutorial 💀",
        "authorDisplayName": "UpdaterMC",
        "publishedAt": "2022-07-31T16:33:02Z",
        "updatedAt": "2022-07-31T16:33:02Z",
        "likeCount": 1,
        "sentimentScore": 0,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgxheZ6h8bKlNhcBj554AaABAg",
        "textDisplay": "<3",
        "authorDisplayName": "Ifmai",
        "publishedAt": "2022-07-30T20:00:32Z",
        "updatedAt": "2022-07-30T20:00:32Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "not available",
        "languageCode": null
    },
    {
        "id": "Ugzc8TpeNiWUE4CO6It4AaABAg",
        "textDisplay": "You are awesome",
        "authorDisplayName": "swaggy",
        "publishedAt": "2022-07-30T19:50:37Z",
        "updatedAt": "2022-07-30T19:50:37Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "hawaiian",
        "languageCode": "haw"
    },
    {
        "id": "UgwwHhop8wQizecNfvR4AaABAg",
        "textDisplay": "Okay I guessss I'll code with you 😒",
        "authorDisplayName": "Noah Warrior",
        "publishedAt": "2022-07-29T18:30:21Z",
        "updatedAt": "2022-07-29T18:30:21Z",
        "likeCount": 0,
        "sentimentScore": -2,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgwJ0iM4EqjR20ho7Q14AaABAg",
        "textDisplay": "Hey Jackie big fan! Please make a video on your Amazon interview Experience.How did you practice DSA and all.",
        "authorDisplayName": "Arghyadeep Dhar",
        "publishedAt": "2022-07-29T17:40:33Z",
        "updatedAt": "2022-07-29T17:40:33Z",
        "likeCount": 0,
        "sentimentScore": 5,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgxJU8Sa6tMfooul9BB4AaABAg",
        "textDisplay": "I'm a simp thats why I opened this video",
        "authorDisplayName": "Vlad Neshkoda",
        "publishedAt": "2022-07-29T15:58:40Z",
        "updatedAt": "2022-07-29T15:58:40Z",
        "likeCount": 0,
        "sentimentScore": 0,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugz-oyic-wEj28QjJVB4AaABAg",
        "textDisplay": "thankyou for exposing front egg,,now i feel like eating eggs😋😋",
        "authorDisplayName": "Wanyoike Danny",
        "publishedAt": "2022-07-29T13:50:11Z",
        "updatedAt": "2022-07-29T13:50:11Z",
        "likeCount": 0,
        "sentimentScore": 1,
        "language": "pidgin",
        "languageCode": "en"
    },
    {
        "id": "Ugwps76rZL4J1wAg8ZV4AaABAg",
        "textDisplay": "Your code is on point. What I have liked to see is, how you planned the whole thing, including research, mockups.",
        "authorDisplayName": "Ikem Krueger",
        "publishedAt": "2022-07-29T12:46:49Z",
        "updatedAt": "2022-07-29T12:46:49Z",
        "likeCount": 0,
        "sentimentScore": 2,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugz-MMxfmwuGC_6Hm2Z4AaABAg",
        "textDisplay": "She hella cute though",
        "authorDisplayName": "Sammy Lemma",
        "publishedAt": "2022-07-29T03:17:59Z",
        "updatedAt": "2022-07-29T03:17:59Z",
        "likeCount": 0,
        "sentimentScore": 2,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugw0vizWt-mrudkBJuB4AaABAg",
        "textDisplay": "Se conseguir ,faz um vídeo em português por favor",
        "authorDisplayName": "Felipe Trolli",
        "publishedAt": "2022-07-28T22:42:58Z",
        "updatedAt": "2022-07-28T22:42:58Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "portuguese",
        "languageCode": "pt"
    },
    {
        "id": "Ugx5T-LI6i7eUfK1lTp4AaABAg",
        "textDisplay": "this video is so inspiring, thank you",
        "authorDisplayName": "Andrii",
        "publishedAt": "2022-07-28T21:14:32Z",
        "updatedAt": "2022-07-28T21:14:32Z",
        "likeCount": 0,
        "sentimentScore": 5,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgzGOQfuQcqseje4sO94AaABAg",
        "textDisplay": "Nice view bb! :)",
        "authorDisplayName": "Jose Aburto",
        "publishedAt": "2022-07-28T16:54:37Z",
        "updatedAt": "2022-07-28T16:54:37Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "czech",
        "languageCode": "cs"
    },
    {
        "id": "UgyzAwfR7QVHuakOMO14AaABAg",
        "textDisplay": "Next time do music more lauder.",
        "authorDisplayName": "Mykola Tokariev",
        "publishedAt": "2022-07-28T16:05:57Z",
        "updatedAt": "2022-07-28T16:05:57Z",
        "likeCount": 0,
        "sentimentScore": 0,
        "language": "pidgin",
        "languageCode": "en"
    },
    {
        "id": "UgywQseLNJi0vWeV4BZ4AaABAg",
        "textDisplay": "Hi\n\nYour last name if santos? You born in Portugal?\n\nThanks",
        "authorDisplayName": "MStekBR",
        "publishedAt": "2022-07-28T15:55:57Z",
        "updatedAt": "2022-07-28T15:55:57Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "tagalog",
        "languageCode": "tl"
    },
    {
        "id": "Ugw1PIEgHjirI4hlfsd4AaABAg",
        "textDisplay": "I look and what do I see.. It's just me making some kind of thing out of shit and sticks...",
        "authorDisplayName": "Do DOS",
        "publishedAt": "2022-07-28T14:44:36Z",
        "updatedAt": "2022-07-28T14:44:36Z",
        "likeCount": 0,
        "sentimentScore": -2,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugz_tc_jAUDiLwgeFcl4AaABAg",
        "textDisplay": "em oh uh meh..",
        "authorDisplayName": "Do DOS",
        "publishedAt": "2022-07-28T14:40:39Z",
        "updatedAt": "2022-07-28T14:40:39Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "portuguese",
        "languageCode": "pt"
    },
    {
        "id": "Ugxt_TqDiH9UekMGBcN4AaABAg",
        "textDisplay": "Nice....Fun fact Santos is a Portuguese Name....Tudo bem?",
        "authorDisplayName": "Flavio Barros",
        "publishedAt": "2022-07-28T13:13:59Z",
        "updatedAt": "2022-07-28T13:13:59Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "portuguese",
        "languageCode": "pt"
    },
    {
        "id": "Ugy5zWcNGisdUTcHzD14AaABAg",
        "textDisplay": "Clean Architecture\nHeads first design patterns\nBuilding microservices\n2 book of system designs interview",
        "authorDisplayName": "MEH MEH",
        "publishedAt": "2022-07-28T11:20:46Z",
        "updatedAt": "2022-07-28T11:21:10Z",
        "likeCount": 0,
        "sentimentScore": 2,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugxy7OcegpOgLpbjMel4AaABAg",
        "textDisplay": "Hey Jackie",
        "authorDisplayName": "Shedfx",
        "publishedAt": "2022-07-28T08:55:11Z",
        "updatedAt": "2022-07-28T08:55:11Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "polish",
        "languageCode": "pl"
    },
    {
        "id": "UgzuSN18UfC_rzbEtmN4AaABAg",
        "textDisplay": "women in CS aren't real everybody knows that",
        "authorDisplayName": "fmstyle",
        "publishedAt": "2022-07-27T22:03:31Z",
        "updatedAt": "2022-07-27T22:03:31Z",
        "likeCount": 0,
        "sentimentScore": 0,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugx6-mIGLAlwcZTHNcd4AaABAg",
        "textDisplay": "only copy paste",
        "authorDisplayName": "deidal0s",
        "publishedAt": "2022-07-27T10:28:34Z",
        "updatedAt": "2022-07-27T10:28:34Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "french",
        "languageCode": "fr"
    },
    {
        "id": "UgwFWE4G3NrDTWGJzXx4AaABAg",
        "textDisplay": "have you tried vue? its great",
        "authorDisplayName": "Shawn Beans",
        "publishedAt": "2022-07-27T08:45:00Z",
        "updatedAt": "2022-07-27T08:45:00Z",
        "likeCount": 0,
        "sentimentScore": 3,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgzOa_knKD9ChGQIiaR4AaABAg",
        "textDisplay": "you are so fucking precious holy shit",
        "authorDisplayName": "BuildRelease",
        "publishedAt": "2022-07-26T07:47:13Z",
        "updatedAt": "2022-07-26T07:47:13Z",
        "likeCount": 0,
        "sentimentScore": -8,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgzbatV3cOd2WiavOzJ4AaABAg",
        "textDisplay": "pretty.",
        "authorDisplayName": "kdrnck",
        "publishedAt": "2022-07-26T02:48:32Z",
        "updatedAt": "2022-07-26T02:48:32Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "czech",
        "languageCode": "cs"
    },
    {
        "id": "Ugxs2qCtMEIkaN3SnO14AaABAg",
        "textDisplay": "can we get engaged ?",
        "authorDisplayName": "HaHa ",
        "publishedAt": "2022-07-25T19:50:57Z",
        "updatedAt": "2022-07-25T19:50:57Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "dutch",
        "languageCode": "nl"
    },
    {
        "id": "UgxNYqPHkV5CyOAQ1lt4AaABAg",
        "textDisplay": "Books, an immersive reading experience, the original metaverse",
        "authorDisplayName": "J Rrrr",
        "publishedAt": "2022-07-25T17:24:03Z",
        "updatedAt": "2022-07-25T17:24:03Z",
        "likeCount": 0,
        "sentimentScore": 0,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugy5BDapOdaVy0xEcn14AaABAg",
        "textDisplay": "\"It took me longer than I was expecting...\" remember this line when starting your new project 😂",
        "authorDisplayName": "Nikolas Malík",
        "publishedAt": "2022-07-25T10:36:24Z",
        "updatedAt": "2022-07-25T10:36:24Z",
        "likeCount": 0,
        "sentimentScore": 1,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgwIP-g8JZVLAJ39qcN4AaABAg",
        "textDisplay": "kj from valorant",
        "authorDisplayName": "Peepeepoopoo224",
        "publishedAt": "2022-07-24T23:43:48Z",
        "updatedAt": "2022-07-24T23:43:48Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "swedish",
        "languageCode": "sv"
    },
    {
        "id": "UgweqrhTpvweqh4WRBN4AaABAg",
        "textDisplay": "Telegram group?",
        "authorDisplayName": "holloway",
        "publishedAt": "2022-07-24T12:52:51Z",
        "updatedAt": "2022-07-24T12:52:51Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "indonesian",
        "languageCode": "id"
    },
    {
        "id": "UgwwtKFPlDQRtwRJAzJ4AaABAg",
        "textDisplay": "You are sweet Jackie.",
        "authorDisplayName": "Athos",
        "publishedAt": "2022-07-23T16:29:43Z",
        "updatedAt": "2022-07-23T16:29:43Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "romanian",
        "languageCode": "ro"
    },
    {
        "id": "Ugx7kZPt8nbyrY3ZHQl4AaABAg",
        "textDisplay": "Great video 👍",
        "authorDisplayName": "AS",
        "publishedAt": "2022-07-23T11:03:36Z",
        "updatedAt": "2022-07-23T11:03:36Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "norwegian",
        "languageCode": "no"
    },
    {
        "id": "UgwD-82AMV9aeW8Q4Xl4AaABAg",
        "textDisplay": "I'm eating wheat while you code, is it not enough for you ?",
        "authorDisplayName": "Nemo Nobody",
        "publishedAt": "2022-07-22T23:26:13Z",
        "updatedAt": "2022-07-22T23:26:13Z",
        "likeCount": 0,
        "sentimentScore": 0,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgxLEOQDx7ZVxP8oDmx4AaABAg",
        "textDisplay": "is that my tricky ear or someone is snorking in the back of the video? that's drives me crazy",
        "authorDisplayName": "Custer Custer",
        "publishedAt": "2022-07-22T21:22:35Z",
        "updatedAt": "2022-07-22T21:22:35Z",
        "likeCount": 0,
        "sentimentScore": -2,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgyvzRkHiMSkThyEb1l4AaABAg",
        "textDisplay": "Nothing is normal in your room",
        "authorDisplayName": "Zoltán Magyar",
        "publishedAt": "2022-07-22T18:07:55Z",
        "updatedAt": "2022-07-22T18:08:03Z",
        "likeCount": 0,
        "sentimentScore": 0,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgxdLmPT41sKDX2ZFlx4AaABAg",
        "textDisplay": "Awesome video but I just have one question. Where did you get those stylish blue light glasses?",
        "authorDisplayName": "Jahkamso Uzoekwe",
        "publishedAt": "2022-07-21T20:41:09Z",
        "updatedAt": "2022-07-21T20:41:09Z",
        "likeCount": 0,
        "sentimentScore": 4,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugz3a3K5k6vqNcR67b14AaABAg",
        "textDisplay": "Coding tutorials are my fav",
        "authorDisplayName": "zed robot",
        "publishedAt": "2022-07-21T00:05:56Z",
        "updatedAt": "2022-07-21T00:05:56Z",
        "likeCount": 2,
        "sentimentScore": 0,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgwFLL01Ip9ztA3XVU94AaABAg",
        "textDisplay": "Jackie can u please do a book review when you finish these? Be good to know which are worth picking up. Great video, take care💗",
        "authorDisplayName": "Zibsticle",
        "publishedAt": "2022-07-20T19:44:05Z",
        "updatedAt": "2022-07-20T19:44:05Z",
        "likeCount": 3,
        "sentimentScore": 9,
        "language": "pidgin",
        "languageCode": "en"
    },
    {
        "id": "UgyDrGNE_UivY77nBa14AaABAg",
        "textDisplay": "code",
        "authorDisplayName": "jos",
        "publishedAt": "2022-07-20T07:20:04Z",
        "updatedAt": "2022-07-20T07:20:04Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "romanian",
        "languageCode": "ro"
    },
    {
        "id": "UgwtSrPwH4Dp8PLMtXp4AaABAg",
        "textDisplay": "Good 👍",
        "authorDisplayName": "coding idea",
        "publishedAt": "2022-07-19T09:17:54Z",
        "updatedAt": "2022-07-19T09:17:54Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "croatian",
        "languageCode": "hr"
    },
    {
        "id": "Ugxmb9eXsQMTsV_h32N4AaABAg",
        "textDisplay": "another video implementing the emojis",
        "authorDisplayName": "Douglas_W",
        "publishedAt": "2022-07-19T02:12:31Z",
        "updatedAt": "2022-07-19T02:12:31Z",
        "likeCount": 0,
        "sentimentScore": 0,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgxTQbb3P8Xkb0Iv_5B4AaABAg",
        "textDisplay": "Jackie! Thanks for creating informative and quality content ☺️",
        "authorDisplayName": "Daniel Borzone",
        "publishedAt": "2022-07-16T23:02:54Z",
        "updatedAt": "2022-07-16T23:02:54Z",
        "likeCount": 6,
        "sentimentScore": 4,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgwhTnV966glu-g691l4AaABAg",
        "textDisplay": "Hi. Excellent video. Frontegg is a trial?",
        "authorDisplayName": "juguetes toys",
        "publishedAt": "2022-07-16T19:36:15Z",
        "updatedAt": "2022-07-16T19:36:15Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "portuguese",
        "languageCode": "pt"
    },
    {
        "id": "Ugyy5kzIvkEfSfnGAat4AaABAg",
        "textDisplay": "YaY!",
        "authorDisplayName": "ThugLifeModafocah",
        "publishedAt": "2022-07-16T19:26:47Z",
        "updatedAt": "2022-07-16T19:26:47Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "tagalog",
        "languageCode": "tl"
    },
    {
        "id": "UgwANclsc_KSLUcEbtx4AaABAg",
        "textDisplay": "big props to coding outside of work, I just can't do it 😅",
        "authorDisplayName": "Paul Dionise",
        "publishedAt": "2022-07-15T11:56:22Z",
        "updatedAt": "2022-07-15T11:56:22Z",
        "likeCount": 0,
        "sentimentScore": 1,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgwIotM0xFP0H6q73xZ4AaABAg",
        "textDisplay": "Can we get a apartment tour it’s so jice",
        "authorDisplayName": "Ysl Matthew",
        "publishedAt": "2022-07-14T18:46:57Z",
        "updatedAt": "2022-07-14T18:46:57Z",
        "likeCount": 0,
        "sentimentScore": 0,
        "language": "pidgin",
        "languageCode": "en"
    },
    {
        "id": "Ugx_A0xhcHfkHZGCnlN4AaABAg",
        "textDisplay": "I like your sense humor. Good videos. 😁😁😁",
        "authorDisplayName": "Luis Duarte",
        "publishedAt": "2022-07-14T12:36:07Z",
        "updatedAt": "2022-07-14T12:36:07Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "norwegian",
        "languageCode": "no"
    },
    {
        "id": "UgwwKzsZ2p8m399xYfh4AaABAg",
        "textDisplay": "is this impressive in your portfolio?",
        "authorDisplayName": "Bigbob23",
        "publishedAt": "2022-07-14T00:15:56Z",
        "updatedAt": "2022-07-14T00:15:56Z",
        "likeCount": 0,
        "sentimentScore": 3,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgyEm8QlDKVDg0JiKxJ4AaABAg",
        "textDisplay": "very cool! nice work",
        "authorDisplayName": "Christopher",
        "publishedAt": "2022-07-13T19:51:34Z",
        "updatedAt": "2022-07-13T19:51:34Z",
        "likeCount": 0,
        "sentimentScore": 4,
        "language": "pidgin",
        "languageCode": "en"
    },
    {
        "id": "UgwWj5E5jhT7cYINII14AaABAg",
        "textDisplay": "I loved the video! Just a note for the next one. Put the face cam in the right up or bottom corner since is better to us to look the code.",
        "authorDisplayName": "Emmanuel Kant Duarte",
        "publishedAt": "2022-07-13T08:12:00Z",
        "updatedAt": "2022-07-13T08:12:00Z",
        "likeCount": 0,
        "sentimentScore": 5,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgyoQh0pKrERY4G5bIN4AaABAg",
        "textDisplay": "you are super crack",
        "authorDisplayName": "jose tovar rodriguez",
        "publishedAt": "2022-07-12T02:58:07Z",
        "updatedAt": "2022-07-12T02:58:07Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "italian",
        "languageCode": "it"
    },
    {
        "id": "UgyRoEI_QcE0hU8wMy94AaABAg",
        "textDisplay": "Self taught vibes 🥳",
        "authorDisplayName": "Levi Baraka",
        "publishedAt": "2022-07-11T18:57:12Z",
        "updatedAt": "2022-07-11T18:57:12Z",
        "likeCount": 2,
        "sentimentScore": "not available",
        "language": "estonian",
        "languageCode": "et"
    },
    {
        "id": "UgzK4MebzneBkzmyZzJ4AaABAg",
        "textDisplay": "You forgot trim(), hahahaha",
        "authorDisplayName": "on edge",
        "publishedAt": "2022-07-11T06:51:52Z",
        "updatedAt": "2022-07-11T06:52:27Z",
        "likeCount": 1,
        "sentimentScore": -1,
        "language": "pidgin",
        "languageCode": "en"
    },
    {
        "id": "Ugykn4Kf5usS_yCH0bB4AaABAg",
        "textDisplay": "For when a Rust video, code with you? :)",
        "authorDisplayName": "Luis Gerardo",
        "publishedAt": "2022-07-11T06:46:01Z",
        "updatedAt": "2022-07-11T06:46:01Z",
        "likeCount": 0,
        "sentimentScore": 0,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgwSINxsRqrAg1pde_d4AaABAg",
        "textDisplay": "Te amo",
        "authorDisplayName": "TOMAS MP",
        "publishedAt": "2022-07-11T03:22:03Z",
        "updatedAt": "2022-07-11T03:22:03Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "portuguese",
        "languageCode": "pt"
    },
    {
        "id": "UgyFYpuPeHxecjxnPNx4AaABAg",
        "textDisplay": "subbed because hawt and good conent",
        "authorDisplayName": "Dante Burnett",
        "publishedAt": "2022-07-11T00:17:51Z",
        "updatedAt": "2022-07-11T00:17:51Z",
        "likeCount": 0,
        "sentimentScore": 3,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugw3OgVe6ru4rbR5yxx4AaABAg",
        "textDisplay": "nice work",
        "authorDisplayName": "De Vito Solucoes",
        "publishedAt": "2022-07-10T22:27:19Z",
        "updatedAt": "2022-07-10T22:27:19Z",
        "likeCount": 0,
        "sentimentScore": 3,
        "language": "pidgin",
        "languageCode": "en"
    },
    {
        "id": "UgyXksygcmXz-d2y6dN4AaABAg",
        "textDisplay": "HEAD FIRST DESIGN PATTERNS is the BEST book out there!",
        "authorDisplayName": "GoodGuy",
        "publishedAt": "2022-07-10T14:16:41Z",
        "updatedAt": "2022-07-10T14:16:41Z",
        "likeCount": 0,
        "sentimentScore": 3,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugy-tZZ-Ww0HaV52idZ4AaABAg",
        "textDisplay": "Ok, I like your channel. That's really cool.\nI don't speak portuguese like you or your other subs but you've a great community and video topics.\n\nGreetings from Venezuela/France/Spain.",
        "authorDisplayName": "Justin",
        "publishedAt": "2022-07-10T13:15:03Z",
        "updatedAt": "2022-07-10T13:15:03Z",
        "likeCount": 0,
        "sentimentScore": 10,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugwk46ryK91vjA9d5h14AaABAg",
        "textDisplay": "Hi Can you please suggest or make some roadmap video about what to learn to be a software engineer?",
        "authorDisplayName": "Tejas singh",
        "publishedAt": "2022-07-10T11:18:55Z",
        "updatedAt": "2022-07-10T11:18:55Z",
        "likeCount": 1,
        "sentimentScore": 1,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgwUCakZrVtGXY6f97V4AaABAg",
        "textDisplay": "❤️ It's good to know that pretty women program too",
        "authorDisplayName": "DANMAGNUZ",
        "publishedAt": "2022-07-10T10:06:34Z",
        "updatedAt": "2022-07-10T10:06:34Z",
        "likeCount": 0,
        "sentimentScore": 4,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgwSa96sOUc7oxVaef94AaABAg",
        "textDisplay": "Your content is amazing Jackie, I get to learn a lot from you💯💟",
        "authorDisplayName": "Bryan Dylan",
        "publishedAt": "2022-07-10T08:13:46Z",
        "updatedAt": "2022-07-10T08:13:46Z",
        "likeCount": 3,
        "sentimentScore": 4,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugwci9of4ueyD9996Ql4AaABAg",
        "textDisplay": "Thank you for the book recommendations. I am in fact reading „Clean Architecture“ at the moment. Next will be about architecture documentation with arc42, and the microservices book you mentioned is already in my Amazon list for the next order :-)",
        "authorDisplayName": "Bernhard Krämer",
        "publishedAt": "2022-07-09T20:47:57Z",
        "updatedAt": "2022-07-09T20:47:57Z",
        "likeCount": 1,
        "sentimentScore": 2,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgxhsrmMtbIX2balfsN4AaABAg",
        "textDisplay": "What’s screen model do you have?",
        "authorDisplayName": "Aldo Munoz",
        "publishedAt": "2022-07-09T15:11:02Z",
        "updatedAt": "2022-07-09T15:11:02Z",
        "likeCount": 0,
        "sentimentScore": 0,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgxzBzFK6WJBc50Z9EN4AaABAg",
        "textDisplay": "Good",
        "authorDisplayName": "Luis Gerardo",
        "publishedAt": "2022-07-09T14:41:21Z",
        "updatedAt": "2022-07-09T14:41:21Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "croatian",
        "languageCode": "hr"
    },
    {
        "id": "Ugzn_57qwJPIW8fbOVh4AaABAg",
        "textDisplay": "could you please put the camera in  another place ?",
        "authorDisplayName": "Gabriel Chaves Valverde",
        "publishedAt": "2022-07-09T03:21:29Z",
        "updatedAt": "2022-07-09T03:21:29Z",
        "likeCount": 0,
        "sentimentScore": 1,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgzswaR9XVgBp84Ci1N4AaABAg",
        "textDisplay": "I love watching your videos. Pls take blog videos much more.  Heeyy yaaa from turkey",
        "authorDisplayName": "Mustafa Sarıgöl",
        "publishedAt": "2022-07-08T20:56:54Z",
        "updatedAt": "2022-07-08T20:56:54Z",
        "likeCount": 0,
        "sentimentScore": 3,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgyiVSnXI3YzO6zuIgJ4AaABAg",
        "textDisplay": "After 4 minutes of coding...my back hurts 🤔😁",
        "authorDisplayName": "George",
        "publishedAt": "2022-07-08T16:44:18Z",
        "updatedAt": "2022-07-08T16:44:18Z",
        "likeCount": 0,
        "sentimentScore": -2,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgxV0qs7GgH9Sjx-0854AaABAg",
        "textDisplay": "olá jackie gosto muito do teu canal, como portugues a viver em portugal gostava de te dar a ideia de falares sobre como alguem como eu pode ir para o UK e arranjar emprego. ainda estou a procura do meu primeiro emprego, mas tenciono um dia ir para ai.",
        "authorDisplayName": "Wrong Name",
        "publishedAt": "2022-07-08T15:01:43Z",
        "updatedAt": "2022-07-08T15:01:43Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "portuguese",
        "languageCode": "pt"
    },
    {
        "id": "UgzRJmE0XdHHHQnRMmx4AaABAg",
        "textDisplay": "Finalmente um vídeo mais técnico 😍 Estou a aprender Javascript/ Node.js/ React/ React Native e vou definitivamente usar o teu vídeo para desenvolver essa mini app para o meu primeiro mini projeto em javascript! Continua o bom trabalho! 😁",
        "authorDisplayName": "Luana Mendonça",
        "publishedAt": "2022-07-08T13:19:27Z",
        "updatedAt": "2022-07-08T13:19:44Z",
        "likeCount": 4,
        "sentimentScore": "not available",
        "language": "portuguese",
        "languageCode": "pt"
    },
    {
        "id": "Ugz8-xc-sYiEu2r8t0l4AaABAg",
        "textDisplay": "the closer your face is to the screen the harder you are thinking +1",
        "authorDisplayName": "Joe Burgess",
        "publishedAt": "2022-07-08T10:26:29Z",
        "updatedAt": "2022-07-08T10:26:29Z",
        "likeCount": 0,
        "sentimentScore": 0,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugz6pQgWyPKMq93ksnR4AaABAg",
        "textDisplay": "Just recently finished reading clean architecture, and i am now on the building microservices one. Definitily recomend both of them! Love your videos!",
        "authorDisplayName": "Bernardo Cardoso",
        "publishedAt": "2022-07-08T09:05:05Z",
        "updatedAt": "2022-07-08T09:05:05Z",
        "likeCount": 3,
        "sentimentScore": 5,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgybteiMpQ4xcIZIta94AaABAg",
        "textDisplay": "Well done jackie, great video🙌🏼",
        "authorDisplayName": "santiago verx",
        "publishedAt": "2022-07-08T07:09:16Z",
        "updatedAt": "2022-07-08T07:09:16Z",
        "likeCount": 0,
        "sentimentScore": 3,
        "language": "pidgin",
        "languageCode": "en"
    },
    {
        "id": "UgygD6Rf_u_siULJoOh4AaABAg",
        "textDisplay": "Great work, but I think we should have started with some architecture or design diagrams for the project? Don’t you agree? 😀 Maybe for version two you could use AWS services like API gateway, lambda, dynamo. Ps: don’t forget your back exercise and stretches if you don’t want back pain.",
        "authorDisplayName": "Lucian Baciu",
        "publishedAt": "2022-07-08T06:07:13Z",
        "updatedAt": "2022-07-08T12:29:34Z",
        "likeCount": 1,
        "sentimentScore": 6,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugw16v331AVI88eX1-B4AaABAg",
        "textDisplay": "Frontegg looks good",
        "authorDisplayName": "ryou zhang",
        "publishedAt": "2022-07-08T05:48:08Z",
        "updatedAt": "2022-07-08T05:48:08Z",
        "likeCount": 1,
        "sentimentScore": "not available",
        "language": "icelandic",
        "languageCode": "isl"
    },
    {
        "id": "UgyCuB7pN8J-2MmOEXd4AaABAg",
        "textDisplay": "so sweet😻",
        "authorDisplayName": "Eye of Sauron",
        "publishedAt": "2022-07-08T03:48:29Z",
        "updatedAt": "2022-07-08T03:48:29Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "slovene",
        "languageCode": "sl"
    },
    {
        "id": "UgxwdabIQ8HhBy2Bunl4AaABAg",
        "textDisplay": "Unless you want to be bombarded with spam Jackie, you might want to blur/cut out your emails :)",
        "authorDisplayName": "Omar Mo",
        "publishedAt": "2022-07-08T03:38:16Z",
        "updatedAt": "2022-07-08T03:38:16Z",
        "likeCount": 1,
        "sentimentScore": -1,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugx6qTcR5Fq1z9POZ9t4AaABAg",
        "textDisplay": "love ur content :) keep up!!",
        "authorDisplayName": "Salam Haider",
        "publishedAt": "2022-07-08T01:24:10Z",
        "updatedAt": "2022-07-08T01:24:10Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "french",
        "languageCode": "fr"
    },
    {
        "id": "UgyXHKou9q36WTqboCt4AaABAg",
        "textDisplay": "Always happy to see one of your videos Jackie.",
        "authorDisplayName": "Jonas Abarca Ponce",
        "publishedAt": "2022-07-07T22:51:33Z",
        "updatedAt": "2022-07-07T22:51:33Z",
        "likeCount": 1,
        "sentimentScore": 3,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugw-4Bm_lEsQZm7Tws14AaABAg",
        "textDisplay": "Please do more of these! I was literally watching a bunch of code with me videos yesterday for the first time and was stoked that you came out with one today. Thanks for the inspiration :)",
        "authorDisplayName": "kaleb420blazit",
        "publishedAt": "2022-07-07T22:12:28Z",
        "updatedAt": "2022-07-07T22:12:28Z",
        "likeCount": 3,
        "sentimentScore": 5,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgzZ47AIlDG7eZ_2mel4AaABAg",
        "textDisplay": "Yay More videos like that!!",
        "authorDisplayName": "Douglas Vinícius",
        "publishedAt": "2022-07-07T20:57:30Z",
        "updatedAt": "2022-07-07T20:57:30Z",
        "likeCount": 0,
        "sentimentScore": 2,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgyBQCUCSoE8Px6sRyl4AaABAg",
        "textDisplay": "You probably don't want to expose your personal email addresses and frontegg clientId etc",
        "authorDisplayName": "ComfyCosi",
        "publishedAt": "2022-07-07T20:51:51Z",
        "updatedAt": "2022-07-07T20:51:51Z",
        "likeCount": 0,
        "sentimentScore": -2,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgyOCdjur8OtFUeM4hF4AaABAg",
        "textDisplay": "Love your videos Jackie! <3 Your videos keeps me motivated to become a self-taught web dev, nothing is impossible <3",
        "authorDisplayName": "Lotniq",
        "publishedAt": "2022-07-07T20:09:20Z",
        "updatedAt": "2022-07-07T20:09:20Z",
        "likeCount": 2,
        "sentimentScore": 5,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugw5CV_-OFdgl9qvzX14AaABAg",
        "textDisplay": "Love it. :)",
        "authorDisplayName": "Charles",
        "publishedAt": "2022-07-07T20:02:13Z",
        "updatedAt": "2022-07-07T20:02:13Z",
        "likeCount": 0,
        "sentimentScore": 3,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugxi7IGFSIUH3c_-hnB4AaABAg",
        "textDisplay": "Regarding the chat app, I have some advance tips. If you care about performance, you can try adding virtualization library (eg. Virtuoso) to handle thousands of chat messages via windowing. Another tips is chat app usually require rich-text editor to allow complex text manipulation (there are a bunch of RTE libraries out there). There are also many more cool stuff about chat app like pagination/load more messages, message status (delivered, sent, failed, read), context reply, media message and URL (with link preview) and more!\n\nPS: I really love Telegram UI UX. Pixel perfect with awesome scrolling behavior 😎",
        "authorDisplayName": "Toni kroos 92",
        "publishedAt": "2022-07-07T18:22:59Z",
        "updatedAt": "2022-07-07T18:22:59Z",
        "likeCount": 0,
        "sentimentScore": 15,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgzsmclBvkqjIjTDoqV4AaABAg",
        "textDisplay": "Oh dear nobody should judge someone who is learning and sharing new things. You've done a great job explaining the stuff 😄🤓\n\nI believe every devs can relate to the scene where you got stuck in the code. Sometimes what we have to do is take some time off, reflect, and then bounce back when we're ready 🌞",
        "authorDisplayName": "Toni kroos 92",
        "publishedAt": "2022-07-07T18:18:49Z",
        "updatedAt": "2022-07-07T18:18:49Z",
        "likeCount": 5,
        "sentimentScore": 5,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgxInNSbb_V-8clYGuZ4AaABAg",
        "textDisplay": "Nice vid, how long did it take to make it?",
        "authorDisplayName": "Milad Haghpanah",
        "publishedAt": "2022-07-07T18:16:11Z",
        "updatedAt": "2022-07-07T18:16:11Z",
        "likeCount": 0,
        "sentimentScore": 3,
        "language": "pidgin",
        "languageCode": "en"
    },
    {
        "id": "UgwW9URmcN0YfI01jdh4AaABAg",
        "textDisplay": "MERRY ME PLZ  :D",
        "authorDisplayName": "GC Entertainment",
        "publishedAt": "2022-07-07T17:52:12Z",
        "updatedAt": "2022-07-07T17:52:12Z",
        "likeCount": 1,
        "sentimentScore": "not available",
        "language": "albanian",
        "languageCode": "sq"
    },
    {
        "id": "UgzUOLOfS6v6U-pc7xN4AaABAg",
        "textDisplay": "I could stare at you for hours, not understanding anything about coding, listening the sounds of the keyboard and be happy! 😁😁😍😍",
        "authorDisplayName": "Michele Bagnoli",
        "publishedAt": "2022-07-07T17:35:08Z",
        "updatedAt": "2022-07-07T17:35:31Z",
        "likeCount": 0,
        "sentimentScore": 3,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgwttPrJoUH9fG9v3EB4AaABAg",
        "textDisplay": "What is your typing speed?",
        "authorDisplayName": "A_08",
        "publishedAt": "2022-07-07T17:20:31Z",
        "updatedAt": "2022-07-07T17:20:31Z",
        "likeCount": 1,
        "sentimentScore": 0,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugz6vWTr2JLjoM5Ul5t4AaABAg",
        "textDisplay": "what is your vscode theme?",
        "authorDisplayName": "Mr. A",
        "publishedAt": "2022-07-07T17:13:30Z",
        "updatedAt": "2022-07-07T17:13:30Z",
        "likeCount": 1,
        "sentimentScore": 0,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgzlauiLJgG1GL3aEh54AaABAg",
        "textDisplay": "How long took to you finish the project?",
        "authorDisplayName": "Mr. A",
        "publishedAt": "2022-07-07T17:09:57Z",
        "updatedAt": "2022-07-07T17:09:57Z",
        "likeCount": 0,
        "sentimentScore": 0,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugwnf1prMry7_NzvYY54AaABAg",
        "textDisplay": "Seus vídeos ajudam a dar uma motivada a continuar estudando e buscando melhores oportunidades de emprego na área. Abraços do Brasil!",
        "authorDisplayName": "Renan Lopes",
        "publishedAt": "2022-07-07T17:07:51Z",
        "updatedAt": "2022-07-07T17:07:51Z",
        "likeCount": 6,
        "sentimentScore": "not available",
        "language": "portuguese",
        "languageCode": "pt"
    },
    {
        "id": "Ugw8IKFI8ThUUi445oJ4AaABAg",
        "textDisplay": "Just a question. Would you want to do a video going through your vsCode extensions and preferred dev tools?",
        "authorDisplayName": "Daniel Nagy",
        "publishedAt": "2022-07-07T16:33:02Z",
        "updatedAt": "2022-07-07T16:33:02Z",
        "likeCount": 132,
        "sentimentScore": 1,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgwgOI-Y5IYaLrUlhll4AaABAg",
        "textDisplay": "Wow jackie good going ❤️❤️",
        "authorDisplayName": "Jyotsna Tiwari",
        "publishedAt": "2022-07-07T16:32:03Z",
        "updatedAt": "2022-07-07T16:32:03Z",
        "likeCount": 0,
        "sentimentScore": 7,
        "language": "pidgin",
        "languageCode": "en"
    },
    {
        "id": "UgwqCx72IjRoDQOJ5ct4AaABAg",
        "textDisplay": "Jackie is so cute, and great react app.",
        "authorDisplayName": "Vu Linh Quach",
        "publishedAt": "2022-07-07T16:31:56Z",
        "updatedAt": "2022-07-07T16:31:56Z",
        "likeCount": 0,
        "sentimentScore": 5,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugw7b1esZ9uobByzl2h4AaABAg",
        "textDisplay": "Nice explanation!!\n- Subscriber from India",
        "authorDisplayName": "Rudrapratap Singh Chouhan CS_073",
        "publishedAt": "2022-07-07T16:28:07Z",
        "updatedAt": "2022-07-07T16:28:07Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "latin",
        "languageCode": "la"
    },
    {
        "id": "UgzhipBtqdWTLDAem5J4AaABAg",
        "textDisplay": "que Vaniaa.Uno encantan tus videos. Bendiciones hermosa Celina que Dios te cuide donde quiera  los mortalesa abian apreciado tan hermosa mujer",
        "authorDisplayName": "Миша Фомилов",
        "publishedAt": "2022-07-07T16:25:42Z",
        "updatedAt": "2022-07-07T16:25:42Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "spanish",
        "languageCode": "es"
    },
    {
        "id": "UgyZ32Wwjg4zVrqWXPV4AaABAg",
        "textDisplay": "👍🏻 gj",
        "authorDisplayName": "sepehr seddiq",
        "publishedAt": "2022-07-07T16:22:23Z",
        "updatedAt": "2022-07-07T16:22:23Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "albanian",
        "languageCode": "sq"
    },
    {
        "id": "UgzHfahosr5qDUlevip4AaABAg",
        "textDisplay": "Now I feel like buying those books too, have only read headfirst out of these😂",
        "authorDisplayName": "Rahul Shetty",
        "publishedAt": "2022-07-07T16:21:24Z",
        "updatedAt": "2022-07-07T16:21:24Z",
        "likeCount": 0,
        "sentimentScore": 2,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgwRMDisbOQF00o4zcJ4AaABAg",
        "textDisplay": "13:13 definitely this chat is a good exercise for developing sockets skills. I also struggled a lot when I had to implement a Chat for a hiring process, I did a great job and rejected by experience, but that's a cool app to have in the portfolio. It's a solid base for a greater application",
        "authorDisplayName": "Daniel Chísica",
        "publishedAt": "2022-07-07T16:16:57Z",
        "updatedAt": "2022-07-07T16:16:57Z",
        "likeCount": 19,
        "sentimentScore": 9,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "Ugx7xQgCX-LMnCWH17V4AaABAg",
        "textDisplay": "Hey jackie ! great app, I like your videos!",
        "authorDisplayName": "Bryan Granado",
        "publishedAt": "2022-07-07T16:07:11Z",
        "updatedAt": "2022-07-07T16:07:11Z",
        "likeCount": 1,
        "sentimentScore": "not available",
        "language": "norwegian",
        "languageCode": "no"
    },
    {
        "id": "UgzPd_KGEzjtNuAVGtl4AaABAg",
        "textDisplay": "Gosto muito de assistir o seus vídeos, espero evoluir bastante na área de programação.",
        "authorDisplayName": "Viniboyfull",
        "publishedAt": "2022-07-07T15:58:41Z",
        "updatedAt": "2022-07-07T15:58:41Z",
        "likeCount": 1,
        "sentimentScore": "not available",
        "language": "portuguese",
        "languageCode": "pt"
    },
    {
        "id": "UgyZMyxUNUdHwMuZtjd4AaABAg",
        "textDisplay": "amazing video Jackie!",
        "authorDisplayName": "Thiago Mowszet",
        "publishedAt": "2022-07-07T15:53:02Z",
        "updatedAt": "2022-07-07T15:53:02Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "dutch",
        "languageCode": "nl"
    },
    {
        "id": "UgxoZPM_VbIieveRolp4AaABAg",
        "textDisplay": "Love these video 🔥🔥👍 Love your content 😍",
        "authorDisplayName": "kushal shingote (iOS Software Engineer📱)",
        "publishedAt": "2022-07-07T15:47:46Z",
        "updatedAt": "2022-07-07T15:47:46Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "french",
        "languageCode": "fr"
    },
    {
        "id": "Ugz8nUC4qfiCk8KBKAl4AaABAg",
        "textDisplay": "Did you create all the styles for the chat or did you use some kind of library or inspiration?",
        "authorDisplayName": "Daniel Chísica",
        "publishedAt": "2022-07-07T15:46:41Z",
        "updatedAt": "2022-07-07T15:46:41Z",
        "likeCount": 1,
        "sentimentScore": 4,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgwlBir9JlTowfAqwoZ4AaABAg",
        "textDisplay": "Tbh you are so beautiful and smart. Dream girl 🥺",
        "authorDisplayName": "wudj Noah",
        "publishedAt": "2022-07-07T15:43:17Z",
        "updatedAt": "2022-07-07T15:43:17Z",
        "likeCount": 0,
        "sentimentScore": 5,
        "language": "pidgin",
        "languageCode": "en"
    },
    {
        "id": "UgxBJ-pkZUDdX4pMAQl4AaABAg",
        "textDisplay": "Please Ghana but currently in Saudi so am need your help",
        "authorDisplayName": "Maahi Ziblim",
        "publishedAt": "2022-07-07T15:43:10Z",
        "updatedAt": "2022-07-07T15:43:10Z",
        "likeCount": 0,
        "sentimentScore": 3,
        "language": "english",
        "languageCode": "en"
    },
    {
        "id": "UgzgQKR8KnTBPi6m3LR4AaABAg",
        "textDisplay": "I like this kind of video ✌🏻",
        "authorDisplayName": "Universe Code",
        "publishedAt": "2022-07-07T15:42:47Z",
        "updatedAt": "2022-07-07T15:42:47Z",
        "likeCount": 7,
        "sentimentScore": 4,
        "language": "pidgin",
        "languageCode": "en"
    },
    {
        "id": "Ugz2-Xcvi3oeE-18fQB4AaABAg",
        "textDisplay": "Hii",
        "authorDisplayName": "Diego Delgado",
        "publishedAt": "2022-07-07T15:40:14Z",
        "updatedAt": "2022-07-07T15:40:14Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "somali",
        "languageCode": "so"
    },
    {
        "id": "Ugyl9y8AwzrbPYSKncR4AaABAg",
        "textDisplay": "Good morning Beautiful 😘😘",
        "authorDisplayName": "Maahi Ziblim",
        "publishedAt": "2022-07-07T15:38:55Z",
        "updatedAt": "2022-07-07T15:38:55Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "cebuano",
        "languageCode": "ceb"
    },
    {
        "id": "Ugwwt_SW4wqiYa9w-Zh4AaABAg",
        "textDisplay": "🤍",
        "authorDisplayName": "Nobitha",
        "publishedAt": "2022-07-07T15:38:11Z",
        "updatedAt": "2022-07-07T15:38:11Z",
        "likeCount": 0,
        "sentimentScore": "not available",
        "language": "not available",
        "languageCode": null
    }
]